name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:



    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Configure CMake


      run: cmake -A Win32 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build

      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - uses: actions/upload-artifact@v3

      with:

        name: EditorWaveform-build

        path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}








